# Use an official Python image as the base
FROM python:3.12

# Set the working directory
WORKDIR /app

# Copy the application files
COPY . .

# Install dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Install Nginx
RUN apt update && apt install -y nginx

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the ports for FastAPI (8000) and Nginx (80)
EXPOSE 80 8000

# Start Nginx and FastAPI together
CMD service nginx start && uvicorn app.main:app --host 0.0.0.0 --port 8000