name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main


jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest

  deploy:
    name: delpoy
    runs-on: ubuntu-latest
    needs: test  
    if: github.event_name == 'push'  
    steps:
      - name: Trigger Deployment on Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"